// Mocks generated by Mockito 5.4.6 from annotations
// in audio_service_platform_interface/test/method_channel_audio_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:audio_service_platform_interface/audio_service_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetChildrenResponse_0 extends _i1.SmartFake
    implements _i2.GetChildrenResponse {
  _FakeGetChildrenResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMediaItemResponse_1 extends _i1.SmartFake
    implements _i2.GetMediaItemResponse {
  _FakeGetMediaItemResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResponse_2 extends _i1.SmartFake
    implements _i2.SearchResponse {
  _FakeSearchResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioHandlerCallbacks].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioHandlerCallbacks extends _i1.Mock
    implements _i2.AudioHandlerCallbacks {
  MockAudioHandlerCallbacks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> prepare(_i2.PrepareRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> prepareFromMediaId(_i2.PrepareFromMediaIdRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromMediaId,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> prepareFromSearch(_i2.PrepareFromSearchRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromSearch,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> prepareFromUri(_i2.PrepareFromUriRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromUri,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> play(_i2.PlayRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #play,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playFromMediaId(_i2.PlayFromMediaIdRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromMediaId,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playFromSearch(_i2.PlayFromSearchRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromSearch,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playFromUri(_i2.PlayFromUriRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromUri,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playMediaItem(_i2.PlayMediaItemRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #playMediaItem,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pause(_i2.PauseRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> click(_i2.ClickRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #click,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stop(_i2.StopRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addQueueItem(_i2.AddQueueItemRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItem,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertQueueItem(_i2.InsertQueueItemRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertQueueItem,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeQueueItem(_i2.RemoveQueueItemRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQueueItem,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeQueueItemAt(_i2.RemoveQueueItemAtRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQueueItemAt,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipToNext(_i2.SkipToNextRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipToNext,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipToPrevious(_i2.SkipToPreviousRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipToPrevious,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> fastForward(_i2.FastForwardRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #fastForward,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rewind(_i2.RewindRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #rewind,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipToQueueItem(_i2.SkipToQueueItemRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipToQueueItem,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seek(_i2.SeekRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setRating(_i2.SetRatingRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setCaptioningEnabled(
          _i2.SetCaptioningEnabledRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCaptioningEnabled,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setRepeatMode(_i2.SetRepeatModeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepeatMode,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setShuffleMode(_i2.SetShuffleModeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShuffleMode,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seekBackward(_i2.SeekBackwardRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #seekBackward,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seekForward(_i2.SeekForwardRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #seekForward,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setSpeed(_i2.SetSpeedRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<dynamic> customAction(_i2.CustomActionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #customAction,
          [request],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<void> onTaskRemoved(_i2.OnTaskRemovedRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onTaskRemoved,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> onNotificationDeleted(
          _i2.OnNotificationDeletedRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onNotificationDeleted,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> onNotificationClicked(
          _i2.OnNotificationClickedRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onNotificationClicked,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> onAndroidForegroundStartFailed(
          _i2.OnAndroidForegroundStartFailedRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAndroidForegroundStartFailed,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.GetChildrenResponse> getChildren(
          _i2.GetChildrenRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildren,
          [request],
        ),
        returnValue: _i3.Future<_i2.GetChildrenResponse>.value(
            _FakeGetChildrenResponse_0(
          this,
          Invocation.method(
            #getChildren,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.GetChildrenResponse>);

  @override
  _i3.Future<_i2.GetMediaItemResponse> getMediaItem(
          _i2.GetMediaItemRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaItem,
          [request],
        ),
        returnValue: _i3.Future<_i2.GetMediaItemResponse>.value(
            _FakeGetMediaItemResponse_1(
          this,
          Invocation.method(
            #getMediaItem,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.GetMediaItemResponse>);

  @override
  _i3.Future<_i2.SearchResponse> search(_i2.SearchRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [request],
        ),
        returnValue: _i3.Future<_i2.SearchResponse>.value(_FakeSearchResponse_2(
          this,
          Invocation.method(
            #search,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.SearchResponse>);

  @override
  _i3.Future<void> androidSetRemoteVolume(
          _i2.AndroidSetRemoteVolumeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidSetRemoteVolume,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> androidAdjustRemoteVolume(
          _i2.AndroidAdjustRemoteVolumeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidAdjustRemoteVolume,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
